repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
      - id: mypy
        additional_dependencies:
          - "types-python-dateutil==2.8.19.6"
          - "types-requests==2.28.11.8"
          - "types-setuptools==65.7.0.3"
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.11.5
    hooks:
      - id: isort
        args: [ "--profile", "black" ]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8.git
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [ --ignore=W503 ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: [ --py37-plus ]
